.vsconfig

sphere commit

---

Assets/Prefabs/Periodic_table/Al.prefab
Assets/Prefabs/Periodic_table/Ar.prefab
Assets/Prefabs/Periodic_table/B.prefab
Assets/Prefabs/Periodic_table/Be.prefab
Assets/Prefabs/Periodic_table/C.prefab
Assets/Prefabs/Periodic_table/Ca.prefab
Assets/Prefabs/Periodic_table/Cl.prefab
Assets/Prefabs/Periodic_table/F.prefab
Assets/Prefabs/Periodic_table/H.prefab
Assets/Prefabs/Periodic_table/He.prefab
Assets/Prefabs/Periodic_table/K.prefab
Assets/Prefabs/Periodic_table/Li.prefab
Assets/Prefabs/Periodic_table/Mg.prefab
Assets/Prefabs/Periodic_table/N.prefab
Assets/Prefabs/Periodic_table/Na.prefab
Assets/Prefabs/Periodic_table/Ne.prefab
Assets/Prefabs/Periodic_table/O.prefab
Assets/Prefabs/Periodic_table/P.prefab
Assets/Prefabs/Periodic_table/S.prefab
Assets/Prefabs/Periodic_table/Si.prefab
Assets/Prefabs/element/B_element.prefab
Assets/Prefabs/element/Ca_element.prefab
Assets/Scenes/BasicScene.unity

Change Asset Pivot2

---

Assets/Scenes/BasicScene.unity

feat: 실험목록/물 생성반응식 내용 추가

---

Assets/Prefabs/UIprefabs/AllTestCase 1.prefab
Assets/Prefabs/UIprefabs/AllTestCase 1.prefab.meta
Assets/Scenes/SampleScene.unity

화학식 수정, 화학 반응식 목록 위치 수정, 이전 버튼(PreviousButton) 2NaClMenu까지 추가 완료

fix: 실험목록창 수정

---

Assets/Prefabs/UIprefabs/TestCaseUI_New.prefab
Assets/Prefabs/UIprefabs/TestCaseUI_New.prefab.meta
Assets/Scenes/SampleScene.unity

TestCaseUI prefab 수정 후 생성

---

Assets/Prefabs/Elements/MakeMolcule_trigger.meta
Assets/Prefabs/Elements/MakeMolcule_trigger/H2O_Trigger.prefab
Assets/Prefabs/Elements/MakeMolcule_trigger/H2O_Trigger.prefab.meta
Assets/Prefabs/Elements/MakeMolcule_trigger/H2_Trigger.prefab
Assets/Prefabs/Elements/MakeMolcule_trigger/H2_Trigger.prefab.meta
Assets/Prefabs/material/Orbit.mat
Assets/Prefabs/material/Orbit.mat.meta
Assets/Scripts/Element/Molcule/Action.cs
Assets/Scripts/Element/Molcule/Action.cs.meta
Assets/Scripts/Element/Molcule/Molcule_Trigger.cs
Assets/Scripts/Element/Molcule/Molcule_Trigger.cs.meta
ProjectSettings/QualitySettings.asset

임시 애니메이션 추가

---

Assets/Prefabs/UIprefabs/BondTC 1.prefab
Assets/Prefabs/UIprefabs/BondTC 1.prefab.meta
Assets/Prefabs/UIprefabs/BondTC.prefab
Assets/Prefabs/UIprefabs/BondTC.prefab.meta

create : 공유결합 & 이온결합 GUI

---

Assets/Prefabs/UIprefabs/BondTC_Complete.prefab
Assets/Prefabs/UIprefabs/BondTC_Complete.prefab.meta

이온 결합 GUI 완성

---

Assets/Prefabs/UIprefabs/Bond_Modify.prefab
Assets/Prefabs/UIprefabs/Bond_Modify.prefab.meta

공유결합 이온결합 GUI 버그 수정

---

Assets/Prefabs/Elements/Molecule/molecule/Cl2_Molecule.prefab
Assets/Prefabs/Elements/Molecule/molecule/F2_Molecule.prefab
Assets/Prefabs/Elements/Molecule/molecule/H2_Molecule.prefab
Assets/Prefabs/Elements/Molecule/molecule/HCl_Molecule.prefab
Assets/Prefabs/Elements/Molecule/molecule/N2_Molecule.prefab

분자 몇개 콜리더 바꿈

---

Assets/Prefabs/Elements/MakeMolcule_trigger/covalent_bond/AlCl3_Trigger.prefab
Assets/Prefabs/Elements/MakeMolcule_trigger/covalent_bond/CH4_Trigger.prefab
Assets/Prefabs/Elements/MakeMolcule_trigger/covalent_bond/CO2_Trigger.prefab
Assets/Prefabs/Elements/MakeMolcule_trigger/covalent_bond/Cl2_Trigger.prefab
Assets/Prefabs/Elements/MakeMolcule_trigger/covalent_bond/F2_Trigger.prefab
Assets/Prefabs/Elements/MakeMolcule_trigger/covalent_bond/H2O_Trigger.prefab
Assets/Prefabs/Elements/MakeMolcule_trigger/covalent_bond/H2_Trigger.prefab
Assets/Prefabs/Elements/MakeMolcule_trigger/covalent_bond/HCl_Trigger.prefab
Assets/Prefabs/Elements/MakeMolcule_trigger/covalent_bond/N2_Trigger.prefab
Assets/Prefabs/Elements/MakeMolcule_trigger/covalent_bond/NH3_Trigger.prefab
Assets/Prefabs/Elements/MakeMolcule_trigger/covalent_bond/O2_Trigger.prefab
Assets/Prefabs/Elements/MakeMolcule_trigger/covalent_bond/SiO2_Trigger.prefab
Assets/Prefabs/Elements/MakeMolcule_trigger/ionic_bond/CaF2_Trigger.prefab
Assets/Prefabs/Elements/MakeMolcule_trigger/ionic_bond/LiCl_Trigger.prefab
Assets/Prefabs/Elements/MakeMolcule_trigger/ionic_bond/MgO_Trigger.prefab
Assets/Prefabs/Elements/MakeMolcule_trigger/ionic_bond/NaCl_Trigger.prefab
Assets/Prefabs/Elements/MakeMolcule_trigger/ionic_bond/NaF_Trigger.prefab
Assets/Prefabs/Elements/Molecule/molecule/ionic/CaF2_Molecule.prefab
Assets/Prefabs/Elements/Molecule/molecule/ionic/LiCl_Molecule.prefab
Assets/Prefabs/Elements/Molecule/molecule/ionic/MgO_Molecule.prefab
Assets/Prefabs/Elements/Molecule/molecule/ionic/NaCl_Molecule.prefab
Assets/Prefabs/Elements/Molecule/molecule/ionic/NaF_Molecule.prefab
Assets/Prefabs/Lab.prefab
Assets/Scripts/Element/Molcule/After_Generator.cs
Assets/Scripts/Element/Molcule/After_Generator.cs.meta
Assets/Scripts/Element/Molcule/Make_Molcule.cs
Assets/Scripts/Element/Molcule/Make_ionic_molcule.cs
Assets/Scripts/Element/Molcule/Molcule_Ionic_Trigger.cs
Assets/Scripts/Element/Molcule/Molcule_Trigger.cs
ProjectSettings/QualitySettings.asset

모든 트리거 수정 완

---

Assets/Prefabs/Canvas/Al-Canvas.prefab
Assets/Prefabs/Canvas/Ar-Canvas.prefab
Assets/Prefabs/Canvas/B-Canvas.prefab
Assets/Prefabs/Canvas/Be-Canvas.prefab
Assets/Prefabs/Canvas/C-Canvas.prefab
Assets/Prefabs/Canvas/Ca-Canvas.prefab
Assets/Prefabs/Canvas/Cl-Canvas.prefab
Assets/Prefabs/Canvas/F-Canvas.prefab
Assets/Prefabs/Canvas/H-Canvas.prefab
Assets/Prefabs/Canvas/He-Canvas.prefab
Assets/Prefabs/Canvas/K-Canvas.prefab
Assets/Prefabs/Canvas/Li-Canvas.prefab
Assets/Prefabs/Canvas/Mg-Canvas.prefab
Assets/Prefabs/Canvas/N-Canvas.prefab
Assets/Prefabs/Canvas/Na-Canvas.prefab
Assets/Prefabs/Canvas/Ne-Canvas.prefab
Assets/Prefabs/Canvas/O-Canvas.prefab
Assets/Prefabs/Canvas/P-Canvas.prefab
Assets/Prefabs/Canvas/S-Canvas.prefab
Assets/Prefabs/Canvas/Si-Canvas.prefab

canvas 사이즈

---

Assets/Prefabs/Elements/MakeMolcule_trigger/covalent_bond/CH4_Trigger.prefab
Assets/Prefabs/Elements/Orbit_Electron/Covalent.meta
Assets/Prefabs/Elements/Orbit_Electron/Covalent/Convalent_CH4.prefab
Assets/Prefabs/Elements/Orbit_Electron/Covalent/Convalent_CH4.prefab.meta
Assets/Prefabs/Elements/Orbit_Electron/Covalent/Convalent_H2O.prefab
Assets/Prefabs/Elements/Orbit_Electron/Covalent/Convalent_H2O.prefab.meta
Assets/Prefabs/Elements/Orbit_Electron/Covalent/Covalent_AlCl3.prefab
Assets/Prefabs/Elements/Orbit_Electron/Covalent/Covalent_AlCl3.prefab.meta
Assets/Prefabs/Elements/Orbit_Electron/Covalent/Covalent_CO2.prefab
Assets/Prefabs/Elements/Orbit_Electron/Covalent/Covalent_CO2.prefab.meta
Assets/Prefabs/Elements/Orbit_Electron/Covalent/Covalent_Cl2.prefab
Assets/Prefabs/Elements/Orbit_Electron/Covalent/Covalent_Cl2.prefab.meta
Assets/Prefabs/Elements/Orbit_Electron/Covalent/Covalent_F2.prefab
Assets/Prefabs/Elements/Orbit_Electron/Covalent/Covalent_F2.prefab.meta
Assets/Prefabs/Elements/Orbit_Electron/Covalent/Covalent_H2.prefab
Assets/Prefabs/Elements/Orbit_Electron/Covalent/Covalent_H2.prefab.meta
Assets/Prefabs/Elements/Orbit_Electron/Covalent/Covalent_HCl.prefab
Assets/Prefabs/Elements/Orbit_Electron/Covalent/Covalent_HCl.prefab.meta
Assets/Prefabs/Elements/Orbit_Electron/Covalent/Covalent_N2.prefab
Assets/Prefabs/Elements/Orbit_Electron/Covalent/Covalent_N2.prefab.meta
Assets/Prefabs/Elements/Orbit_Electron/Covalent/Covalent_NH3.prefab
Assets/Prefabs/Elements/Orbit_Electron/Covalent/Covalent_NH3.prefab.meta
Assets/Prefabs/Elements/Orbit_Electron/Covalent/Covalent_O2.prefab
Assets/Prefabs/Elements/Orbit_Electron/Covalent/Covalent_O2.prefab.meta
Assets/Prefabs/Elements/Orbit_Electron/Covalent/Covalent_SiO2.prefab
Assets/Prefabs/Elements/Orbit_Electron/Covalent/Covalent_SiO2.prefab.meta
Assets/Scripts/Element/Molcule/Action.cs
Assets/Scripts/Element/Molcule/After_Generator.cs

프리팹 추가 및 버그 수정

---

Assets/Prefabs/Scale/Glass3.mat
Assets/Scenes/SampleScene.unity
Assets/Scripts/AtomSlot.meta
Assets/Scripts/AtomSlot/AtomSlot.cs
Assets/Scripts/AtomSlot/AtomSlot.cs.meta
Assets/Scripts/AtomSlot/CheckButton.cs
Assets/Scripts/AtomSlot/CheckButton.cs.meta
Assets/Scripts/AtomSlot/Reaction.cs
Assets/Scripts/AtomSlot/Reaction.cs.meta
ProjectSettings/QualitySettings.asset

스크립트 위치 Assets>Scripts>AtomSlot

검사대 스크립트 생성 및 적용

---

Assets/Prefabs/Lab.prefab
Assets/Prefabs/mole_descript/covalent_des/AlCl3-Canvas.prefab
Assets/Scenes/SampleScene.unity
Assets/Scripts/AtomSlot/BarManager.cs
Assets/Scripts/AtomSlot/BarManager.cs.meta

실험목록 진행막대 제작

---

Assets/Prefabs/Elements/element/original_size/Al_element.prefab
Assets/Prefabs/Elements/element/original_size/Ar_element.prefab
Assets/Prefabs/Elements/element/original_size/B_element.prefab
Assets/Prefabs/Elements/element/original_size/Be_element.prefab
Assets/Prefabs/Elements/element/original_size/C_element.prefab
Assets/Prefabs/Elements/element/original_size/Ca_element.prefab
Assets/Prefabs/Elements/element/original_size/Cl_element.prefab
Assets/Prefabs/Elements/element/original_size/F_element.prefab
Assets/Prefabs/Elements/element/original_size/H_element.prefab
Assets/Prefabs/Elements/element/original_size/He_element.prefab
Assets/Prefabs/Elements/element/original_size/K_element.prefab
Assets/Prefabs/Elements/element/original_size/Li_element.prefab
Assets/Prefabs/Elements/element/original_size/Mg_element .prefab
Assets/Prefabs/Elements/element/original_size/N_element.prefab
Assets/Prefabs/Elements/element/original_size/Na_element.prefab
Assets/Prefabs/Elements/element/original_size/Ne_element.prefab
Assets/Prefabs/Elements/element/original_size/O_element.prefab
Assets/Prefabs/Elements/element/original_size/P_element.prefab
Assets/Prefabs/Elements/element/original_size/S_element.prefab
Assets/Prefabs/Elements/element/original_size/Si_element.prefab
Assets/Prefabs/Help.prefab
Assets/Prefabs/Lab.prefab
Assets/Scenes/SampleScene.unity

클리어 했을때 추가 로직

---

Assets/Physics Lab/Materials/DeviceB_DIFF.mat
Assets/Physics Lab/Materials/DeviceC_DIFF.mat
Assets/Prefabs/Lab.prefab
ProjectSettings/QualitySettings.asset

Lab Sencne

---

Assets/Prefabs/Card/GameManager.prefab
Assets/Scripts/CardGame/Game/GameManager.cs
Assets/Scripts/CardGame/sj.meta
Assets/Scripts/CardGame/sj/imsi_Draw.cs
Assets/Scripts/CardGame/sj/imsi_Draw.cs.meta
ProjectSettings/QualitySettings.asset

무슨 이상한 버그 생겨서 고침

---

Assets/Prefabs/Card/CardSetting.prefab
Assets/Prefabs/Card/GameManager.prefab
Assets/Prefabs/Monsters/H20_Monster.prefab
Assets/Scenes/SampleScene.unity
Assets/Scripts/CardGame/Game/GameManager.cs
Assets/Scripts/CardGame/Game/MyDraw.cs
Assets/Scripts/Monster/MoleculeSpawner.cs
Assets/Scripts/Start/LayManager.cs
Assets/Scripts/Start/TurnLight.cs

게임메니져와 몬스터 스폰 연결

---

Assets/Prefabs/Card/Card_prefabs/He.prefab
Assets/Prefabs/Card/Card_prefabs/Li.prefab
Assets/Prefabs/Card/Card_prefabs/Li.prefab.meta
Assets/Prefabs/Card/GameManager.prefab
Assets/Scripts/CardGame/Game/GameManager.cs
Assets/Scripts/CardGame/Game/MyDraw.cs
ProjectSettings/QualitySettings.asset

게임메니져 거의 완성

---

Assets/Prefabs/Card/Monsters/H20_Monster.prefab
Assets/Prefabs/Card/Monsters/다운로드.png.meta
Assets/Scripts/CardGame/Game/GameMonster.cs
ProjectSettings/QualitySettings.asset

H2O몬스터 hp바 수정

---

Assets/Prefabs/Card/Monsters/AlCl3_Monster.prefab
Assets/Prefabs/Card/Monsters/CH4_Monster.prefab
Assets/Prefabs/Card/Monsters/CO2_Monster.prefab
Assets/Prefabs/Card/Monsters/CaF2_Monster.prefab
Assets/Prefabs/Card/Monsters/Cl2_Monster.prefab
Assets/Prefabs/Card/Monsters/F2_Monster.prefab
Assets/Prefabs/Card/Monsters/H20_Monster.prefab
Assets/Prefabs/Card/Monsters/H2_Monster.prefab
Assets/Prefabs/Card/Monsters/HCl_Monster.prefab
Assets/Prefabs/Card/Monsters/LiCl_Monster.prefab
Assets/Prefabs/Card/Monsters/MgO_Monster.prefab
Assets/Prefabs/Card/Monsters/N2_Monster.prefab
Assets/Prefabs/Card/Monsters/NH3_Monster.prefab
Assets/Prefabs/Card/Monsters/NaCl_Monster.prefab
Assets/Prefabs/Card/Monsters/NaF_Monster.prefab
Assets/Prefabs/Card/Monsters/O2_Monster.prefab
Assets/Prefabs/Card/Monsters/SiO2_Monster.prefab
Assets/Scripts/CardGame/Game/Cards/O.cs
Assets/Scripts/CardGame/Game/GameCard.cs
Assets/Scripts/CardGame/Game/GameManager.cs
ProjectSettings/QualitySettings.asset

산소의 고유효과 구현
